spring.application.name=eureka-service

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

eureka.server.enable-self-preservation=${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:false}
eureka.server.eviction-interval-timer-in-ms=${EUREKA_SERVER_EVICTION_INTERVAL_MS:5000}
